  server:
    port: "8088"
  spring:
    application:
      name: shopApp
    datasource:
      url: jdbc:mysql://localhost:3307/shopApp?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  api:
    prefix: "api/v1"

